import "./globals.css";
import type { Metadata } from "next";
import { Playfair, Open_Sans } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const playfair = Playfair({ subsets: ["latin"], variable: "--font-play-fair" });

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Medcare Medical",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${playfair.variable} relative`}>
        <header>
          <Navbar />
        </header>
        <main className="mt-[4rem]">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
